# Generated by Django 4.1 on 2025-12-26 10:00

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(upload_to='achievements/')),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('excerpt', models.TextField(max_length=500)),
                ('content', models.TextField()),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='blog/')),
                ('video', models.FileField(blank=True, help_text='Video file for project walkthrough', null=True, upload_to='blog/videos/')),
                ('author', models.CharField(default='NationNineRealty', max_length=100)),
                ('category', models.CharField(default='Real Estate', max_length=100)),
                ('views', models.IntegerField(default=0)),
                ('published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('state', models.CharField(default='Maharashtra', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Cities',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='clients/')),
                ('website', models.URLField(blank=True, null=True)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ClientUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, default='', max_length=100)),
                ('last_name', models.CharField(blank=True, default='', max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('mobile', models.CharField(max_length=15, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_registered', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(max_length=20)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Flat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flat_number', models.CharField(help_text='e.g., A-101, B-201', max_length=50)),
                ('flat_type', models.CharField(choices=[('1bhk', '1 BHK'), ('1.5bhk', '1.5 BHK'), ('2bhk', '2 BHK'), ('2.5bhk', '2.5 BHK'), ('3bhk', '3 BHK'), ('3.5bhk', '3.5 BHK'), ('4bhk', '4 BHK'), ('4.5bhk', '4.5 BHK'), ('5bhk', '5 BHK'), ('5.5bhk', '5.5 BHK')], max_length=20)),
                ('floor_number', models.IntegerField()),
                ('carpet_area', models.DecimalField(decimal_places=2, help_text='Carpet area in SQFT', max_digits=10)),
                ('built_up_area', models.DecimalField(blank=True, decimal_places=2, help_text='Built-up area in SQFT', max_digits=10, null=True)),
                ('super_area', models.DecimalField(blank=True, decimal_places=2, help_text='Super area in SQFT', max_digits=10, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('price_per_sqft', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('available', 'Available'), ('sold', 'Sold'), ('reserved', 'Reserved'), ('hold', 'Hold')], default='available', max_length=20)),
                ('facing', models.CharField(blank=True, help_text='e.g., North, South, East, West', max_length=50, null=True)),
                ('balcony', models.BooleanField(default=False)),
                ('parking', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['floor_number', 'flat_number'],
            },
        ),
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(max_length=15)),
                ('otp_code', models.CharField(max_length=6)),
                ('is_verified', models.BooleanField(default=False)),
                ('purpose', models.CharField(choices=[('signup', 'Sign Up'), ('login', 'Login'), ('contact', 'Contact Form')], default='login', max_length=20)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('property_type', models.CharField(choices=[('residential', 'Residential'), ('commercial', 'Commercial'), ('resale', 'Resale')], max_length=20)),
                ('transaction_type', models.CharField(default='buy', help_text='All projects are for Buy only', max_length=10)),
                ('is_hot', models.BooleanField(default=False, help_text='Mark as Hot property')),
                ('project_status', models.CharField(blank=True, choices=[('pre_launch', 'Pre Launch'), ('new_launch', 'New Launch'), ('new_tower_launch', 'New Tower Launch'), ('ready_to_move', 'Ready To Move'), ('nearing_possession', 'Nearing Possession')], max_length=30, null=True)),
                ('available_flat_types', models.CharField(blank=True, help_text='Comma-separated flat types: 1bhk,2bhk,3bhk', max_length=200, null=True)),
                ('location', models.CharField(max_length=200)),
                ('city_name', models.CharField(default='Pune', help_text='Fallback if city FK is null', max_length=100)),
                ('state', models.CharField(default='Maharashtra', max_length=100)),
                ('description', models.TextField()),
                ('cover_image', models.ImageField(upload_to='projects/')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('views', models.IntegerField(default=0)),
                ('featured', models.BooleanField(default=False)),
                ('id_number', models.CharField(blank=True, max_length=50, null=True)),
                ('about_listing', models.TextField(blank=True, null=True)),
                ('map_location', models.TextField(blank=True, null=True)),
                ('rera_number', models.CharField(blank=True, max_length=100, null=True)),
                ('land_area', models.CharField(blank=True, help_text='e.g., 2.2 ACRES', max_length=100, null=True)),
                ('amenities_area', models.CharField(blank=True, help_text='e.g., 25K SQ FT', max_length=100, null=True)),
                ('total_units', models.IntegerField(blank=True, null=True)),
                ('total_towers', models.IntegerField(blank=True, null=True)),
                ('developer_name', models.CharField(blank=True, max_length=200, null=True)),
                ('structure', models.CharField(blank=True, max_length=200, null=True)),
                ('flooring', models.TextField(blank=True, null=True)),
                ('kitchen', models.TextField(blank=True, null=True)),
                ('electrical', models.TextField(blank=True, null=True)),
                ('doors', models.TextField(blank=True, null=True)),
                ('plaster', models.TextField(blank=True, null=True)),
                ('windows', models.TextField(blank=True, null=True)),
                ('toilet', models.TextField(blank=True, null=True)),
                ('security_safety', models.TextField(blank=True, null=True)),
                ('paint', models.TextField(blank=True, null=True)),
                ('plumbing', models.TextField(blank=True, null=True)),
                ('lift', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='api.city')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=200)),
                ('designation', models.CharField(default='Happy Customer', max_length=200)),
                ('review_text', models.TextField()),
                ('rating', models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Tower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., A, B, C or Tower 1, Tower 2', max_length=100)),
                ('tower_number', models.CharField(blank=True, help_text='e.g., A Wing, B Wing', max_length=50, null=True)),
                ('total_floors', models.IntegerField(default=0)),
                ('parking_floors', models.IntegerField(default=0)),
                ('residential_floors', models.IntegerField(default=0)),
                ('refugee_floors', models.IntegerField(default=0, help_text='Refuge floors')),
                ('per_floor_flats', models.IntegerField(default=0)),
                ('total_lifts', models.IntegerField(default=0)),
                ('total_stairs', models.IntegerField(default=0)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('rera_completion_date', models.DateField(blank=True, null=True)),
                ('rera_number', models.CharField(blank=True, max_length=100, null=True)),
                ('booking_status', models.CharField(choices=[('booking_open', 'Booking Open'), ('booking_closed', 'Booking Closed'), ('sold_out', 'Sold Out')], default='booking_open', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='towers', to='api.project')),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TowerAmenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('icon', models.CharField(blank=True, max_length=100)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amenities', to='api.tower')),
            ],
            options={
                'verbose_name_plural': 'Tower Amenities',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='projects/gallery/')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('category', models.CharField(choices=[('inside_view', 'Inside View'), ('left_view', 'Left View'), ('right_view', 'Right View'), ('front_view', 'Front View'), ('back_view', 'Back View'), ('amenity', 'Amenity'), ('gym', 'Gym'), ('lawn', 'Lawn'), ('pool', 'Pool'), ('playground', 'Playground'), ('lobby', 'Lobby'), ('other', 'Other')], default='other', max_length=50)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='api.project')),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectEnquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('mobile', models.CharField(max_length=20)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(help_text='Project Specific Enquiry', on_delete=django.db.models.deletion.CASCADE, related_name='Enquiries', to='api.project')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.clientuser')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectAmenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('icon', models.CharField(blank=True, max_length=100)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amenities', to='api.project')),
            ],
            options={
                'verbose_name_plural': 'Project Amenities',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddIndex(
            model_name='otp',
            index=models.Index(fields=['mobile', 'otp_code'], name='api_otp_mobile_9e0804_idx'),
        ),
        migrations.AddField(
            model_name='flat',
            name='tower',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flats', to='api.tower'),
        ),
        migrations.AddField(
            model_name='contact',
            name='project',
            field=models.ForeignKey(blank=True, help_text='Project the customer is interested in', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contacts', to='api.project'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='project',
            field=models.ForeignKey(blank=True, help_text='Related project for this blog post', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blog_posts', to='api.project'),
        ),
        migrations.AlterUniqueTogether(
            name='tower',
            unique_together={('project', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='flat',
            unique_together={('tower', 'flat_number')},
        ),
    ]
