# Generated by Django 4.1 on 2025-12-05 19:08

from django.db import migrations, models
import django.db.models.deletion


def migrate_city_data(apps, schema_editor):
    """Create City objects from existing city_name values and link projects"""
    City = apps.get_model('api', 'City')
    Project = apps.get_model('api', 'Project')
    
    # Get all unique city names from existing projects
    projects = Project.objects.all()
    city_names = set()
    
    for project in projects:
        # Use city_name field which should have the old city value
        if project.city_name:
            city_names.add(project.city_name)
    
    # Create City objects
    city_map = {}
    for city_name in city_names:
        if city_name:
            city, created = City.objects.get_or_create(
                name=city_name,
                defaults={'state': 'Maharashtra', 'is_active': True}
            )
            city_map[city_name] = city
    
    # Update projects to link to City objects
    for project in projects:
        if project.city_name and project.city_name in city_map:
            project.city = city_map[project.city_name]
            project.save(update_fields=['city'])


def migrate_city_data_reverse(apps, schema_editor):
    """Reverse migration - set city_name from city FK"""
    Project = apps.get_model('api', 'Project')
    
    for project in Project.objects.all():
        if project.city:
            project.city_name = project.city.name
            project.save(update_fields=['city_name'])


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_project_about_listing_project_doors_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('state', models.CharField(default='Maharashtra', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Cities',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Tower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., A, B, C or Tower 1, Tower 2', max_length=100)),
                ('tower_number', models.CharField(blank=True, help_text='e.g., A Wing, B Wing', max_length=50, null=True)),
                ('total_floors', models.IntegerField(default=0)),
                ('parking_floors', models.IntegerField(default=0)),
                ('residential_floors', models.IntegerField(default=0)),
                ('refugee_floors', models.IntegerField(default=0, help_text='Refuge floors')),
                ('per_floor_flats', models.IntegerField(default=0)),
                ('total_lifts', models.IntegerField(default=0)),
                ('total_stairs', models.IntegerField(default=0)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('rera_completion_date', models.DateField(blank=True, null=True)),
                ('rera_number', models.CharField(blank=True, max_length=100, null=True)),
                ('booking_status', models.CharField(choices=[('booking_open', 'Booking Open'), ('booking_closed', 'Booking Closed'), ('sold_out', 'Sold Out')], default='booking_open', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='project',
            name='amenities_area',
            field=models.CharField(blank=True, help_text='e.g., 25K SQ FT', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='available_flat_types',
            field=models.CharField(blank=True, help_text='Comma-separated flat types: 1bhk,2bhk,3bhk', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='city_name',
            field=models.CharField(default='Pune', help_text='Fallback if city FK is null', max_length=100),
        ),
        migrations.AddField(
            model_name='project',
            name='developer_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='land_area',
            field=models.CharField(blank=True, help_text='e.g., 2.2 ACRES', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='possession_year',
            field=models.IntegerField(blank=True, help_text='Expected possession year (2025, 2026, etc.)', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='project_status',
            field=models.CharField(blank=True, choices=[('pre_launch', 'Pre Launch'), ('new_launch', 'New Launch'), ('new_tower_launch', 'New Tower Launch'), ('ready_to_move', 'Ready To Move'), ('nearing_possession', 'Nearing Possession')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='rera_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='total_towers',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='total_units',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='TowerAmenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('icon', models.CharField(blank=True, max_length=100)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amenities', to='api.tower')),
            ],
            options={
                'verbose_name_plural': 'Tower Amenities',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='tower',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='towers', to='api.project'),
        ),
        # Store existing city values in city_name before changing field type
        migrations.RunPython(
            code=lambda apps, schema_editor: None,  # No-op, city_name already added
            reverse_code=lambda apps, schema_editor: None,
        ),
        migrations.AlterField(
            model_name='project',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='api.city'),
        ),
        # Data migration: Create cities from city_name and link projects
        migrations.RunPython(
            code=migrate_city_data,
            reverse_code=migrate_city_data_reverse,
        ),
        # Data migration: Create cities and link projects
        migrations.RunPython(
            code=migrate_city_data,
            reverse_code=migrate_city_data_reverse,
        ),
        migrations.AlterUniqueTogether(
            name='tower',
            unique_together={('project', 'name')},
        ),
        migrations.CreateModel(
            name='Flat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flat_number', models.CharField(help_text='e.g., A-101, B-201', max_length=50)),
                ('flat_type', models.CharField(choices=[('1bhk', '1 BHK'), ('1.5bhk', '1.5 BHK'), ('2bhk', '2 BHK'), ('2.5bhk', '2.5 BHK'), ('3bhk', '3 BHK'), ('3.5bhk', '3.5 BHK'), ('4bhk', '4 BHK'), ('4.5bhk', '4.5 BHK'), ('5bhk', '5 BHK'), ('5.5bhk', '5.5 BHK')], max_length=20)),
                ('floor_number', models.IntegerField()),
                ('carpet_area', models.DecimalField(decimal_places=2, help_text='Carpet area in SQFT', max_digits=10)),
                ('built_up_area', models.DecimalField(blank=True, decimal_places=2, help_text='Built-up area in SQFT', max_digits=10, null=True)),
                ('super_area', models.DecimalField(blank=True, decimal_places=2, help_text='Super area in SQFT', max_digits=10, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('price_per_sqft', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('available', 'Available'), ('sold', 'Sold'), ('reserved', 'Reserved'), ('hold', 'Hold')], default='available', max_length=20)),
                ('facing', models.CharField(blank=True, help_text='e.g., North, South, East, West', max_length=50, null=True)),
                ('balcony', models.BooleanField(default=False)),
                ('parking', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flats', to='api.tower')),
            ],
            options={
                'ordering': ['floor_number', 'flat_number'],
                'unique_together': {('tower', 'flat_number')},
            },
        ),
    ]
