# Generated by Django 4.1 on 2025-12-05 19:08

from django.db import migrations


def migrate_city_data_forward(apps, schema_editor):
    """Create City objects from existing Project.city values and link them"""
    City = apps.get_model('api', 'City')
    Project = apps.get_model('api', 'Project')
    
    # Get all unique city names from existing projects
    # Note: At this point, city is still a CharField in the database
    # We need to access it through raw SQL or handle it differently
    
    # Get all projects
    projects = Project.objects.all()
    
    # Collect unique city names
    city_names = set()
    for project in projects:
        # Access the old city field value
        # Since we're in a migration, we need to use the historical model
        # The city field is still a CharField at this point
        if hasattr(project, 'city') and project.city:
            city_names.add(project.city)
    
    # Create City objects
    city_map = {}
    for city_name in city_names:
        if city_name:
            city, created = City.objects.get_or_create(
                name=city_name,
                defaults={'state': 'Maharashtra', 'is_active': True}
            )
            city_map[city_name] = city
    
    # Update projects to link to City objects
    # But wait - the city field is still CharField, so we can't do this yet
    # We need to do this AFTER the field is changed to FK
    # So this migration needs to run AFTER the AlterField
    pass


def migrate_city_data_reverse(apps, schema_editor):
    """Reverse migration"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_city_tower_project_amenities_area_and_more'),
    ]

    operations = [
        # This will run after 0003, so city is already a FK
        migrations.RunPython(migrate_city_data_forward, migrate_city_data_reverse),
    ]
