# Generated by Django 4.1 on 2025-12-07 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_migrate_city_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(max_length=15)),
                ('otp_code', models.CharField(max_length=6)),
                ('is_verified', models.BooleanField(default=False)),
                ('purpose', models.CharField(choices=[('signup', 'Sign Up'), ('login', 'Login'), ('contact', 'Contact Form')], default='login', max_length=20)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('mobile', models.CharField(max_length=15, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='project',
            name='possession_year',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='project',
            field=models.ForeignKey(blank=True, help_text='Related project for this blog post', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blog_posts', to='api.project'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='video',
            field=models.FileField(blank=True, help_text='Video file for project walkthrough', null=True, upload_to='blog/videos/'),
        ),
        migrations.AddField(
            model_name='contact',
            name='project',
            field=models.ForeignKey(blank=True, help_text='Project the customer is interested in', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contacts', to='api.project'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='transaction_type',
            field=models.CharField(default='buy', help_text='All projects are for Buy only', max_length=10),
        ),
        migrations.AddIndex(
            model_name='otp',
            index=models.Index(fields=['mobile', 'otp_code'], name='api_otp_mobile_9e0804_idx'),
        ),
    ]
