# Generated by Django 4.1 on 2025-12-07 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_otp_user_remove_project_possession_year_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='status',
        ),
        migrations.AddField(
            model_name='project',
            name='is_hot',
            field=models.BooleanField(default=False, help_text='Mark as Hot property'),
        ),
        migrations.AlterField(
            model_name='project',
            name='property_type',
            field=models.CharField(choices=[('residential', 'Residential'), ('commercial', 'Commercial'), ('resale', 'Resale')], max_length=20),
        ),
    ]
