# Generated by Django 4.1 on 2025-12-07 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_project_status_project_is_hot_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GalleryImage',
        ),
        migrations.DeleteModel(
            name='Service',
        ),
        migrations.DeleteModel(
            name='Statistic',
        ),
    ]
