# Generated by Django 4.1 on 2025-12-22 02:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_rename_is_admin_user_is_registered_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectEnquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=20)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(help_text='Project Specific Enquiry', on_delete=django.db.models.deletion.CASCADE, related_name='Enquiries', to='api.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
