# Generated by Django 4.1 on 2025-12-22 04:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0010_projectenquiry'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectenquiry',
            old_name='phone',
            new_name='mobile',
        ),
        migrations.AddField(
            model_name='projectenquiry',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
